version: '3.8'

services:
  web:
    build: .
    ports:
      - '8002:8002'
    volumes:
      - ./gogensite:/app
    environment:
      - PGSERVICEFILE=/app/.pg_service.conf
      - PGPASSFILE=/app/.pgpass
    env_file: 
      - ./gogensite/.env
