# Generated by Django 4.0.6 on 2022-07-11 14:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gogen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzlelog',
            name='board',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=2), size=5), size=5),
        ),
    ]
