# Generated by Django 4.1.1 on 2023-08-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gogen', '0004_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzlelog',
            name='notes',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
