# Generated by Django 4.2.4 on 2023-08-21 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gogen', '0006_notetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='preset_notes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gogen.notetemplate'),
        ),
    ]
