name: Run Django Tests
concurrency: django_tests
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
  schedule:
    - cron: '0 3 * * *'
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: 2222
        script: |
          cd gogen
          rm -rf test-gogen-app
          git clone https://github.com/Matt-Mcl/gogen test-gogen-app
          cd test-gogen-app
          git checkout ${{github.event.pull_request.head.ref}}
          bash run_action_tests.sh
