name: Run Django Tests
on: 
  push:
    branches: [ master ]
  schedule:
    - cron: '0 3 * * *'
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          cd gogen/prod-gogen-app/gogensite
          git pull
          bash run_prod_tests.sh
