name: Run Django Tests
concurrency: django_tests
on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 3 * * *'
jobs:
  run_tests:
    runs-on: self-hosted
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /tmp
          rm -rf test-gogen-app
          git clone https://github.com/Matt-Mcl/gogen test-gogen-app
          cd test-gogen-app
          echo "Checking out PR branch: ${{github.event.pull_request.head.ref}}"
          git checkout ${{github.event.pull_request.head.ref}}
          bash run_action_tests.sh
