name: Run Django Tests
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
  schedule:
    - cron: '0 3 * * *'
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          cd gogen/test-gogen-app/gogensite
          git pull
          echo "testtestesttesttestesttesttestesttesttestesttesttestesttesttestest"
          echo ${{github.event.pull_request.head.ref}}
          echo "testtestesttesttestesttesttestesttesttestesttesttestesttesttestest"
          git checkout ${{github.event.pull_request.head.ref}}
          bash run_prod_tests.sh
